import { Entity, Column, ManyToOne, JoinColumn, Index, OneToMany } from "typeorm";
import { BaseEntity } from "./Base.entity";
import { AlertType, AlertSeverity, AlertStatus, SharingLevel } from "../types/enums";
import { Sensor } from "./Sensor.entity";
import { Pipeline } from "./Pipeline.entity";
import { Facility } from "./Facility.entity";
import { WorkOrder } from "./WorkOrder.entity";

@Entity("alerts")
@Index(["type", "severity", "status"])
@Index(["sensorId", "timestamp"])
@Index(["status", "severity"])
export class Alert extends BaseEntity {
  @Column({ type: "enum", enum: AlertType })
  type: AlertType;

  @Column({ type: "enum", enum: AlertSeverity })
  severity: AlertSeverity;

  @Column({ type: "enum", enum: AlertStatus, default: AlertStatus.PENDING })
  status: AlertStatus;

  @Column({ type: "varchar", length: 200 })
  title: string;

  @Column({ type: "text", nullable: true })
  description: string;

  @Column({ type: "uuid", nullable: true })
  sensorId: string;

  @Column({ type: "uuid", nullable: true })
  pipelineId: string;

  @Column({ type: "uuid", nullable: true })
  facilityId: string;

  @Column({ type: "numeric", precision: 15, scale: 6, nullable: true })
  readingValue: number;

  @Column({ type: "numeric", precision: 15, scale: 6, nullable: true })
  thresholdValue: number;

  @Column({ type: "timestamp" })
  timestamp: Date;

  @Column({ type: "timestamp", nullable: true })
  acknowledgedAt: Date;

  @Column({ type: "uuid", nullable: true })
  acknowledgedBy: string;

  @Column({ type: "timestamp", nullable: true })
  resolvedAt: Date;

  @Column({ type: "uuid", nullable: true })
  resolvedBy: string;

  @Column({ type: "text", nullable: true })
  resolutionNotes: string;

  @Column({ type: "geometry", nullable: true })
  location: any;

  @Column({ type: "jsonb", nullable: true })
  attributes: Record<string, any>;

  @Column({ type: "boolean", default: false })
  autoGenerated: boolean;

  @Column({ type: "enum", enum: SharingLevel, default: SharingLevel.PRIVATE })
  sharingLevel: SharingLevel;

  @ManyToOne(() => Sensor, (sensor) => sensor.alerts)
  @JoinColumn({ name: "sensorId" })
  sensor: Sensor;

  @ManyToOne(() => Pipeline)
  @JoinColumn({ name: "pipelineId" })
  pipeline: Pipeline;

  @ManyToOne(() => Facility)
  @JoinColumn({ name: "facilityId" })
  facility: Facility;

  @OneToMany(() => WorkOrder, (workOrder) => workOrder.alert)
  workOrders: WorkOrder[];
}
